name: animated_switch
description: Custom animated swith - You can customize and animate the color, text and choose different status icons
version: 0.0.3
homepage: https://github.com/marcosjav/animated_switch

environment:
  sdk: ">=2.18.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
